services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./webdata:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  php:
    image: php:8.0-fpm
    container_name: php-fpm
    volumes:
      - ./webdata:/var/www/html
    networks:
      - app-network

  ftp:
    build: ./ftp
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"  # Passive FTP ports
    volumes:
      - ./webdata/u:/home/ftpusers
      - ./ftp/users.csv:/config/users.csv
    environment:
      FTP_USER_CSV: /config/users.csv
    depends_on:
      - nginx
    networks:
      - app-network

# volumes:
#   webdata:

networks:
  app-network:
    driver: bridge
